// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: id_maker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MakeIDServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"` // ID 生成模式："snowflake" 或 "segment"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeIDServiceRequest) Reset() {
	*x = MakeIDServiceRequest{}
	mi := &file_id_maker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeIDServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeIDServiceRequest) ProtoMessage() {}

func (x *MakeIDServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_id_maker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeIDServiceRequest.ProtoReflect.Descriptor instead.
func (*MakeIDServiceRequest) Descriptor() ([]byte, []int) {
	return file_id_maker_proto_rawDescGZIP(), []int{0}
}

func (x *MakeIDServiceRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type MakeIDServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeIDServiceResponse) Reset() {
	*x = MakeIDServiceResponse{}
	mi := &file_id_maker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeIDServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeIDServiceResponse) ProtoMessage() {}

func (x *MakeIDServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_id_maker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeIDServiceResponse.ProtoReflect.Descriptor instead.
func (*MakeIDServiceResponse) Descriptor() ([]byte, []int) {
	return file_id_maker_proto_rawDescGZIP(), []int{1}
}

func (x *MakeIDServiceResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_id_maker_proto protoreflect.FileDescriptor

const file_id_maker_proto_rawDesc = "" +
	"\n" +
	"\x0eid_maker.proto\x12\x02pb\"*\n" +
	"\x14MakeIDServiceRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\"'\n" +
	"\x15MakeIDServiceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2O\n" +
	"\aIDMaker\x12D\n" +
	"\rMakeIDService\x12\x18.pb.MakeIDServiceRequest\x1a\x19.pb.MakeIDServiceResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_id_maker_proto_rawDescOnce sync.Once
	file_id_maker_proto_rawDescData []byte
)

func file_id_maker_proto_rawDescGZIP() []byte {
	file_id_maker_proto_rawDescOnce.Do(func() {
		file_id_maker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_id_maker_proto_rawDesc), len(file_id_maker_proto_rawDesc)))
	})
	return file_id_maker_proto_rawDescData
}

var file_id_maker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_id_maker_proto_goTypes = []any{
	(*MakeIDServiceRequest)(nil),  // 0: pb.MakeIDServiceRequest
	(*MakeIDServiceResponse)(nil), // 1: pb.MakeIDServiceResponse
}
var file_id_maker_proto_depIdxs = []int32{
	0, // 0: pb.IDMaker.MakeIDService:input_type -> pb.MakeIDServiceRequest
	1, // 1: pb.IDMaker.MakeIDService:output_type -> pb.MakeIDServiceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_id_maker_proto_init() }
func file_id_maker_proto_init() {
	if File_id_maker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_id_maker_proto_rawDesc), len(file_id_maker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_id_maker_proto_goTypes,
		DependencyIndexes: file_id_maker_proto_depIdxs,
		MessageInfos:      file_id_maker_proto_msgTypes,
	}.Build()
	File_id_maker_proto = out.File
	file_id_maker_proto_goTypes = nil
	file_id_maker_proto_depIdxs = nil
}
