// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: id_maker.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IDMaker_MakeIDService_FullMethodName = "/pb.IDMaker/MakeIDService"
)

// IDMakerClient is the client API for IDMaker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IDMakerClient interface {
	MakeIDService(ctx context.Context, in *MakeIDServiceRequest, opts ...grpc.CallOption) (*MakeIDServiceResponse, error)
}

type iDMakerClient struct {
	cc grpc.ClientConnInterface
}

func NewIDMakerClient(cc grpc.ClientConnInterface) IDMakerClient {
	return &iDMakerClient{cc}
}

func (c *iDMakerClient) MakeIDService(ctx context.Context, in *MakeIDServiceRequest, opts ...grpc.CallOption) (*MakeIDServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MakeIDServiceResponse)
	err := c.cc.Invoke(ctx, IDMaker_MakeIDService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IDMakerServer is the server API for IDMaker service.
// All implementations must embed UnimplementedIDMakerServer
// for forward compatibility.
type IDMakerServer interface {
	MakeIDService(context.Context, *MakeIDServiceRequest) (*MakeIDServiceResponse, error)
	mustEmbedUnimplementedIDMakerServer()
}

// UnimplementedIDMakerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIDMakerServer struct{}

func (UnimplementedIDMakerServer) MakeIDService(context.Context, *MakeIDServiceRequest) (*MakeIDServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeIDService not implemented")
}
func (UnimplementedIDMakerServer) mustEmbedUnimplementedIDMakerServer() {}
func (UnimplementedIDMakerServer) testEmbeddedByValue()                 {}

// UnsafeIDMakerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IDMakerServer will
// result in compilation errors.
type UnsafeIDMakerServer interface {
	mustEmbedUnimplementedIDMakerServer()
}

func RegisterIDMakerServer(s grpc.ServiceRegistrar, srv IDMakerServer) {
	// If the following call pancis, it indicates UnimplementedIDMakerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IDMaker_ServiceDesc, srv)
}

func _IDMaker_MakeIDService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeIDServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDMakerServer).MakeIDService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IDMaker_MakeIDService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDMakerServer).MakeIDService(ctx, req.(*MakeIDServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IDMaker_ServiceDesc is the grpc.ServiceDesc for IDMaker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IDMaker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.IDMaker",
	HandlerType: (*IDMakerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeIDService",
			Handler:    _IDMaker_MakeIDService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "id_maker.proto",
}
